name: eng_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MultiroundPro
      fonts:
        - asset: assets/fonts/MultiroundPro.otf


